trigger:
- main

jobs:
- job: build_and_push_data_receiver
  displayName: "Build & Push Data Receiver Image"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: git://autotrader/data-receiver
    clean: true    
  - task: Docker@2
    displayName: Login to Container Registry
    inputs:
      command: login
      containerRegistry: PK_DOCKER_REGISTRY
  - script: |
      docker build -f Dockerfile -t $(PKADD)/data-receiver:$(Build.SourceVersion) .
    displayName: 'Data Receiver Image Build'
  - script: |
      docker push $(PKADD)/data-receiver:$(Build.SourceVersion)
    displayName: 'Pushing the image to Container Registry'
  - bash: |
      git push https://$(GIT_TOKEN)@github.com/reggiev/data-receiver \
            +refs/remotes/origin/main:refs/heads/main --prune
    displayName: 'Copy to Github'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

  # TODO scan the built image for CVEs
  # TODO Configure vault storage for GITHUB_PAT
- job: push_to_github
  displayName: "Push to github"
  pool:
    vmImage: 'ubuntu-latest'

  steps:   
  - checkout: self
  - bash: |
      git push https://$(GIT_TOKEN)@github.com/reggiev/autotrader-pipelines \
            +refs/remotes/origin/main:refs/heads/main --prune
    displayName: 'Copy to Github'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')